name: Force Sync from upstream (gh-pages branch ONLY)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Add upstream remote
      run: |
        git remote add upstream https://github.com/jaywcjlove/reference.git
        git fetch upstream gh-pages

    - name: Force reset local gh-pages to upstream/gh-pages
      run: |
#        git config user.name "github-actions[bot]"
#        git config user.email "github-actions[bot]@users.noreply.github.com"
#        git merge upstream/gh-pages --allow-unrelated-histories -m "Merge upstream "
        git reset --hard upstream/gh-pages
        git push origin gh-pages --force
